### ISSUE TITLE
Build fails with GCC 6.1.1 after latest commit

### ISSUE THREAD

**Issue by miramor** [tome2/tome2#11]
Commit is b3d136333c1b516123cc83e3dc96d4bd79dd52ca

The error message is as follows:

```
/home/proteus/tome2/src/init1.cc: In function ‘errr init_s_info_txt(FILE*)’:
/home/proteus/tome2/src/init1.cc:3147:29: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
    if (NULL == (txt = strchr(s, ':'))) return (1);
                       ~~~~~~^~~~~~~~
make[2]: *** [src/CMakeFiles/game.dir/init1.cc.o] Error 1
make[1]: *** [src/CMakeFiles/game.dir/all] Error 2
make: *** [all] Error 2
```

Cause is obvious enough, but I'll do a bisect to see where this stopped working.

Edit: this might take a while, as there's another ongoing build issue.

**Comment by BardurArantsson** [comment]
This honestly sounds like there's a bug in the strchr() declaration on your system. On my system (GCC 6.2.1, glibc 2.24) it's declared as

```
extern char *strchr (const char *__s, int __c)
```

Are you using some sort of IDE which can show you the exact declaration it's using on your system? (E.g. in QtCreator you can open the project and Ctrl+Click on the call to `strchr` in line 3147 of init1 and it'll take you to the declaration.)

**Comment by miramor** [comment]
From string.h:

```
extern "C++"
{
extern char *strchr (char *__s, int __c)
     __THROW __asm ("strchr") __attribute_pure__ __nonnull ((1));
extern const char *strchr (const char *__s, int __c)
     __THROW __asm ("strchr") __attribute_pure__ __nonnull ((1));

# ifdef __OPTIMIZE__
__extern_always_inline char *
strchr (char *__s, int __c) __THROW
{
  return __builtin_strchr (__s, __c);
}

__extern_always_inline const char *
strchr (const char *__s, int __c) __THROW
{
  return __builtin_strchr (__s, __c);
}
# endif
}

```

**Comment by BardurArantsson** [comment]
Hm. I wonder if it's the *return* type that causing trouble here... maybe it's interfering with overload resolution.

**Comment by BardurArantsson** [comment]
Regardless, can you try changing the "const char *s" in line 3148 (or thereabouts) to "char *"?

**Comment by miramor** [comment]
@BardurArantsson It works with 'const' removed.

**Comment by BardurArantsson** [comment]
OK, thanks for confirming. "Fixed".
