### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by adamreiser** [tome2/tome2#15]
I'm curious about why the Elvish calendar was removed; what was the reason?

**Comment by BardurArantsson** [comment]
I don't there's much other reason than that it got in the way of some refactoring and it's excessive amounts of code for pretty pointless flavor. (IIRC the only instance where it was even used is in the chardump and the ^T command?)

**Comment by adamreiser** [comment]
I liked the calendar. I feel like one of ToME's strengths is its strong (if occasionally idiosyncratic) connection to Arda. But if it gets in the way of keeping the codebase manageable, I suppose I can understand.
