### ISSUE TITLE
No prompt for overwriting savefile

### ISSUE THREAD

**Issue by fph** [tome2/tome2#17]
Today I wanted to create a new throw-away character to test a thing quickly; so I used "new character" in the loading screen, and inadvertently pressed "enter" accepting the default savefile name PLAYER, which was already in use. Apparently this wiped away my old existing character (without asking for confirmation).

You may want to add a check in this case.

**Comment by BardurArantsson** [comment]
Wow, that's pretty bad -- wonder why nobody's found this before!

I'll try to get it fixed this weekend.

**Comment by BardurArantsson** [comment]
Should be fixed. It now just shows a message to the effect that the character already exists and loads it instead of overwriting.

**Comment by BardurArantsson** [comment]
I though about leaving out the message, but that might be confusing... what do you think?

**Comment by fph** [comment]
Thanks for the fix! I approve the message -- explicit is better than implicit.
