### ISSUE TITLE
Skill device calculation

### ISSUE THREAD

**Issue by fph** [tome2/tome2#18]
From `calc_bonuses` in `xtra1.cc`:

	/* Affect Skill -- magic devices (INT) */
	p_ptr->skill_dev += get_skill_scale(SKILL_DEVICE, 20);

	/* Affect Skill -- saving throw (WIS) */
	p_ptr->skill_sav += adj_wis_sav[p_ptr->stat_ind[A_WIS]];

	/* Affect Skill -- digging (STR) */
	p_ptr->skill_dig += adj_str_dig[p_ptr->stat_ind[A_STR]];

	/* Affect Skill -- magic devices (skill) */
	p_ptr->skill_dev += (get_skill_scale(SKILL_DEVICE, 150));

	/* Affect Skill -- saving throw (skill and level) */
	p_ptr->skill_sav += (get_skill_scale(SKILL_SPIRITUALITY, 75));

Shouldn't the first row use `stat_ind[A_INT]`, analogously to the following ones? It seems to me that magic skill device is counted twice instead, and INT has absolutely no effect on magic device usage.

**Comment by BardurArantsson** [comment]
Wow, well spotted. I don't really know this code, but I think this *must* be a mistake. Double-counting SKILL_DEVICE makes very little sense.

I have *no* idea what substituting in adj_int_dev(?) would do, but there's definitely something wrong here.

I'll have a look tomorrow or the day after. Thanks for the report.

**Comment by BardurArantsson** [comment]
Ok, so there *is* no adj_int_dev -- probably because it got replaced by the Magic Device skill :).

Given that the "20" amounts to very little compared to the "150", I think I'll just remove the first line.

**Comment by fph** [comment]
Thanks for this fix, too. I am a bit worried that essentially this is equivalent to giving everyone a 13% penalty on their skill device rolls. The high-level devices seem already difficult enough to use. On the character I am playing now, I have maxed magic-device, and still I have 83% fail on a staff of Genocide...

**Comment by BardurArantsson** [comment]
IIRC it isn't quite linear like that, but do playtest it and file an issue if you think the "penalty" is too severe.

(Note: The changes in master have broken savegames yet again, so make sure you play any current characters to their end before updating. Not breaking samegames all the time is probably going to be a focus for development...)
