### ISSUE TITLE
Compilation fails after latest commit

### ISSUE THREAD

**Issue by RealityWarper** [tome2/tome2#19]
Compilation fails with following output, probably because of [this commit](https://github.com/tome2/tome2/commit/554ff9a63d5d9bc64f668a00b6baa9b91dc41306).

> [  1%] Building CXX object src/squelch/CMakeFiles/squelch.dir/automatizer.cc.o
> [  2%] Building CXX object src/squelch/CMakeFiles/squelch.dir/condition.cc.o
> In file included from /home/filip/tome2/src/squelch/condition.cc:9:0:
> /home/filip/tome2/src/squelch/../game.hpp:68:27: error: declaration of ‘messages Game::messages’ [-fpermissive]
>   messages messages { 2048 };
>                            ^
> In file included from /home/filip/tome2/src/squelch/../game.hpp:10:0,
>                  from /home/filip/tome2/src/squelch/condition.cc:9:
> /home/filip/tome2/src/squelch/../messages.hpp:11:8: error: changes meaning of ‘messages’ from ‘struct messages’ [-fpermissive]
>  struct messages final {
>         ^~~~~~~~
> src/squelch/CMakeFiles/squelch.dir/build.make:86: recipe for target 'src/squelch/CMakeFiles/squelch.dir/condition.cc.o' failed
> make[2]: *** [src/squelch/CMakeFiles/squelch.dir/condition.cc.o] Error 1
> CMakeFiles/Makefile2:344: recipe for target 'src/squelch/CMakeFiles/squelch.dir/all' failed
> make[1]: *** [src/squelch/CMakeFiles/squelch.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

To get it working again change

> messages messages { 2048 };

to

> ::messages messages { 2048 };

in **game.hpp**.

**Comment by BardurArantsson** [comment]
Should be fixed by the commit I pushed just now.

Which compiler was this, btw? I'm just curious because my compiler apparently was able to disambiguate just fine.

**Comment by RealityWarper** [comment]
$ gcc-6 --version
gcc-6 (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
