### ISSUE TITLE
make fails because of some object flag cell

### ISSUE THREAD

**Issue by dchmelik** [tome2/tome2#20]
Make fails because of some C++ thing: [log](https://gist.github.com/dchmelik/8549d68a96375a057cb20a29d7108ae7).

**Comment by BardurArantsson** [comment]
This looks like another case of and old compiler. Which compiler are you using?

**Comment by dchmelik** [comment]
Apparently so.  My current (the most Unix-like) stable distribution has some 5.n, but I see 7.n is out.  The current (testing/unstable) version has that, but it may be a while until my stable version does, especially since I'm using multilib (quasi-official, updated even slower.)
