### ISSUE TITLE
if possible please use boost 1.67 instead of boost 1.54 in tome2 

### ISSUE THREAD

**Issue by shirishag75** [tome2/tome2#33]
Debian is currently using boost 1.67 in testing and in backports. If possible, please use that instead of using the version which is in old-stable. 

https://tracker.debian.org/pkg/boost-defaults

**Comment by BardurArantsson** [comment]
It already works just fine with newer boost. Are you actually seening any compilation problems? If so, please reopen.

**Comment by shirishag75** [comment]
yeah, it says - 

```
~/games/tome2$ cmake .
-- Could NOT find Boost
-- Some or all of the gtk libraries were not found. (missing: GTK2_GTK_LIBRARY GTK2_GTK_INCLUDE_DIR GTK2_GDK_INCLUDE_DIR GTK2_GDKCONFIG_INCLUDE_DIR GTK2_GDK_LIBRARY) 
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
-- The following packages have been found:

 * X11
 * Threads
 * Curses

-- The following packages have not been found:

 * Boost (required version >= 1.54.0)
 * GTK2
 * SDL

-- Configuring done
-- Generating done
-- Build files have been written to: /home/shirish/games/tome2 
```

**Comment by BardurArantsson** [comment]
It works fine with Boost 1.68.0 for me.

Do you have boost-filesystem installed?

**Comment by BardurArantsson** [comment]
That's a successful configure message :). Or, at least, the messages don't have anything to do with Boost :).

You should be able to compile. (But you'll only get the X11 frontend. If you want other frontends you'll have to 

So, I think what needs to be done is to mention the 'boost-filesystem-dev' package. Actually the README does mention libboost-all-dev (for Ubuntu).
