### ISSUE TITLE
please update to use libgtk3 if possible 

### ISSUE THREAD

**Issue by shirishag75** [tome2/tome2#34]
During Debian buster libgtk-2.0.0 will no longer be part of the default install and it seems most applications would have moved to libgtk3.0 - See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883440 for details.

**Comment by BardurArantsson** [comment]
I don't think it's realistic that this will ever happen due to lack of time/manpower. Also, "not installed by default" doesn't mean "not available", I assume?
