### ISSUE TITLE
Does not compile in macOS 11.2, C++14

### ISSUE THREAD

**Issue by kdiez** [tome2/tome2#55]
I do have a patch with a fix, but I am quite new to GitHub and it is not clear to me how to contribute. Any tips? It looks like I need auth/rights to create a branch with the fix.

**Comment by BardurArantsson** [comment]
To create a PR you should Fork the repository, create a branch there with your commit. Once that's done you can navigate to the branch in your own fork. Hope that makes sense :)

There's some more info here:

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by kdiez** [comment]
Understood! @BardurArantsson thanks for pointing me in the right direction :)

**Comment by BardurArantsson** [comment]
@kdiez Did you get it working?

I'm only asking because I don't see any new PR.

**Comment by kdiez** [comment]
@BardurArantsson It compiled fine and I have been playing a few days since, but I haven't had the time yet to publish it yet. I will keep you posted!

**Comment by BardurArantsson** [comment]
Cool, cool cool. Was just curiuous whether you were stuck. If you're just having too much fun playing, then no worries! :smile:

**Comment by kdiez** [comment]
Finally got some time to fork the repo and fix it to make it compile :)
