### ISSUE TITLE
make ends on 'error 2'

### ISSUE THREAD

**Issue by dchmelik** [tome2/tome2#65]
On Slackware64 GNU/Linux 15+current gcc 12.2, making 1e26568b ends on 'error 2': [gist](https://gist.github.com/dchmelik/ddd1e083abd537096dc0d2e425c2d9b2) log.

**Comment by jkatzmewing** [comment]
What OS, compiler, and compiler version?

**Comment by dchmelik** [comment]
> What OS, compiler, and compiler version?

 Slackware64 15+current gcc 12.2

**Comment by BardurArantsson** [comment]
Does it work if you add
```c++
#include <map>
```
just above the `#include <boost/...` line at the top?

**Comment by dchmelik** [comment]
> Does it work if you add
> ```c++
> #include <map>
> ```
> just above the `#include <boost/...` line at the top?

At top of what file(s)?

**Comment by dchmelik** [comment]
> Does it work if you add
> 
> ```c++
> #include <map>
> ```
> 
> just above the `#include <boost/...` line at the top?

In squelch/condition.cc?  Yes.
