### ISSUE TITLE
Shouldn't the current file be wiped before appending macros?

### ISSUE THREAD

**Issue by bridgesense** [tome2/tome2#66]
I have this compiled on Ubuntu Jammy. 

I was having some issues with macros not working after creating them.  I realized that each time I was appending the file according to the on-screen prompt, a new whole set of macros were being appended.  With all the macros duplicated several times, the system wasn't using my most recent changes.

Eventually, I just edited the file by hand, and after reloading the file the new macros seemed to work file.

**Comment by BardurArantsson** [comment]
It's an unfortunate consequence of storing both keymaps and macros in the same file, namely the character's prefs file. If we were to replace-on-save you'd lose macros or keymaps on save of either.

I guess one could try to do something different here, but honestly I've no motivation to work on the C++ codebase at the moment, sorry.
