### ISSUE TITLE
asan/ubsan linkage should probably be moved to debug compile flags

### ISSUE THREAD

**Issue by miramor** [tome2/tome2#8]
With CMAKE_BUILD_TYPE=Release and no changes to CMakeLists:

    $ du -h src/tome-x11 
    44M	src/tome-x11

With the -fsanitize stuff removed from CMakeLists:

    $ du -h src/tome-x11 
    3.7M	src/tome-x11

With just -fsanitize=address, it still bloats up quite a bit:

    $ du -h src/tome-x11 
    7.9M	src/tome-x11

So I think dropping both ubsan and asan from the release flags would be a good idea.

I'd also point out that shared library forms of both asan and ubsan are now available, and can be forced to load via LD_PRELOAD. So on current Linux systems (e.g. Debian Sid), linking against them might not be so helpful anyway.

**Comment by BardurArantsson** [comment]
I'm a bit torn on this... on the one hand ASAN/UBSAN incur a performance penalty[1], but bug reports from UBSAN/ASAN as sooo incredibly useful (as opposed to "it crashes" or just random weird behavior) and actionable that it's almost miraculous.

Not sure what to do here. Would a configure-time switch to actively *disable* be sufficient? So: anyone compiling from source would get the UBSAN/ASAN version by default (but could turn it off with a switch to cmake), but distributions and "more informed users" could turn it off without editing the `CMakeLists.txt`. (Not that I expect many distributions actually carry T2-ah.) What do you think?

[1] I don't think a space argument holds *too* much weight these days what with multi-TB disks, etc. (But I can certainly understand that some people may have download bandwidth issues, so there's that...)

**Comment by miramor** [comment]
Thus my suggestion of moving this stuff to debug flags, i.e. the default when compiling from Git. For the eventual release versions we wouldn't want these libraries sapping performance from e.g. the SDL interface... would we? I don't know. In any case, not a big deal I guess.

**Comment by BardurArantsson** [comment]
I don't think the performance difference is really all that noticable. (IIRC it's on the order of ~1.5x-2x or something like that.)

Maybe I didn't make myself clear enough: What I meant is that one would actively have to do e.g.

```
cmake -DDISABLE_SANITIZE
```

to actively disable sanitizer flags. (So the flags would be present by default if no such switch was given.)
